name: Run Tests

on: [push, pull_request]

jobs:

  test-library:
    uses: quattor/release/.github/workflows/vanilla-scdb.yaml@main

  standard-pan:
    ues: quattor/release/.github/workflows/pan-template-tests.yaml@main
